services:
  posec3d-cue-service:
    image: nex/posec3d-cue-service:latest
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - ORGANIZATION_ID=${ORGANIZATION_ID}
      - DEVICE_ID=${DEVICE_ID}
      - MS3_URL=${MS3_URL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
